name: Remind Dependabot alerts2
on:
  push:
  workflow_dispatch:
env:
  SLACK_USERNAME: DeployBot
  SLACK_ICON: https://github.githubassets.com/images/modules/logos_page/GitHub-Mark.png
  SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK_URL }}

jobs:
  dependabot-notifier2:
    runs-on: ubuntu-latest
    permissions:
      security-events: read
    steps:
      - name: GitHub CLI
        id: get-dependabot-alert
        env:
          GH_TOKEN: ${{ secrets.DEPENDABOT_TOKEN }}
        run: |
          res=$(gh api \
             -H "Accept: application/vnd.github+json" \
             -H "X-GitHub-Api-Version: 2022-11-28" \
             /repos/mtsuchiya/sample01/dependabot/alerts?state=open \
             --jq \
             'map({
                severity: .security_vulnerability.severity,
                package_name: .dependency.package.name,
                created_at: .created_at
              })')
          echo "DEPENDABOT_ALERTS<<EOF" >> "$GITHUB_OUTPUT"
          echo $res >> "$GITHUB_OUTPUT"
          echo "EOF" >> "$GITHUB_OUTPUT"

      - name: get count
        id: get-count
        run: |
          dependabot_alerts="${{ steps.get-dependabot-alert.outputs.DEPENDABOT_ALERTS }}"
          echo "total_count=$(echo \'$dependabot_alerts\' | jq 'length')" >> "$GITHUB_OUTPUT"
          echo "critical_count=$(echo '${{ steps.get-dependabot-alert.outputs.DEPENDABOT_ALERTS }}' | jq '.[] | select(.severity == "critical") | .severity' | wc -l)" >> "$GITHUB_OUTPUT"

      - name: echo count
        run: |
          echo ${{ steps.get-count.outputs.total_count }}
          echo ${{ steps.get-count.outputs.critical_count }}
