name: Remind Dependabot alerts2
on:
  push:
  workflow_dispatch:

jobs:
  dependabot-notifier2:
    runs-on: ubuntu-latest
    permissions:
      security-events: read
    steps:
      - name: Generate token
        id: generate-token
        uses: actions/create-github-app-token@v1
        with:
          app-id: ${{ secrets.APP_ID }}
          private-key: ${{ secrets.PRIVATE_KEY }}

      - name: Get Dependabot alerts
        id: get-dependabot-alerts
        uses: actions/github-script@v7
        with:
          github-token: ${{ steps.generate-token.outputs.token }}
          script: |
            const res = await github.request('GET /repos/{owner}/{repo}/dependabot/alerts', {
              owner: context.repo.owner,
              repo: context.repo.repo,
              headers: {
                'X-GitHub-Api-Version': '2022-11-28'
              }
            })
            return res.data.map((value) => ({
                severity : value.security_vulnerability.severity,
                package_name : value.dependency.package.name
            }))

      - name: Create Slack Message
        id: create-slack-message
        env:
          DEPENDABOT_ALERTS_DATA: ${{ steps.get-dependabot-alerts.outputs.result }}
        uses: actions/github-script@v7
        with:
          result-encoding: string
          script: |
            const {DEPENDABOT_ALERTS_DATA, GITHUB_SERVER_URL, GITHUB_REPOSITORY} = process.env
            const alerts_data = JSON.parse(DEPENDABOT_ALERTS_DATA)
            console.log(alerts_data)
            const totalCount = alerts_data.length
            if (totalCount == 0) {
              return ""
            }
            let a = Object.fromEntries(['critical', 'high', 'medium', 'low'].map(severity => [severity, alerts_data.filter(val => val.severity === severity).length]))
            console.log(a)
            const criticalCount = alerts_data.filter(val => val.severity === 'critical').length
            const highCount = alerts_data.filter(val => val.severity === 'high').length
            const mediumCount = alerts_data.filter(val => val.severity === 'medium').length
            const lowCount = alerts_data.filter(val => val.severity === 'low').length
            console.log(`${totalCount}, ${criticalCount}`)
            const messages = [
              'Dependabot alerts を確認してください。',
              `${GITHUB_SERVER_URL}/${GITHUB_REPOSITORY}/security/dependabot`,
              `total count: ${totalCount}`,
              `high count: ${highCount}`,
              `medium count: ${mediumCount}`,
              `low count: ${lowCount}`
            ]
            console.log(messages.join('\n'))
            return messages.join('\n')

      - name: Slack Notification Dependabot alerts
        uses: rtCamp/action-slack-notify@v2
        if: steps.create-slack-message.outputs.result != ''
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK_URL }}
          SLACK_USERNAME: Dependabot
          SLACK_ICON: https://github.githubassets.com/images/modules/logos_page/GitHub-Mark.png
          SLACK_TITLE: Dependabot alerts
          SLACK_COLOR: good
          ENABLE_ESCAPES: true
          SLACK_MESSAGE: ${{ steps.create-slack-message.outputs.result }}
