name: Remind Dependabot alerts2
on:
  push:
  workflow_dispatch:

jobs:
  dependabot-notifier2:
    runs-on: ubuntu-latest
    permissions:
      security-events: read
    steps:
      - name: Generate token
        id: generate-token
        uses: actions/create-github-app-token@v1
        with:
          app-id: ${{ secrets.APP_ID }}
          private-key: ${{ secrets.PRIVATE_KEY }}

      - uses: actions/github-script@v7
        env:
          TOKEN: ${{ steps.generate-token.outputs.token }}
        with:
          github-token: ${{ steps.generate-token.outputs.token }}
          script: |
            console.log(context)
  
            const res = await github.request('GET /repos/{owner}/{repo}/dependabot/alerts', {
              owner: 'mtsuchiya',
              repo: 'sample01',
              headers: {
                'X-GitHub-Api-Version': '2022-11-28'
              }
            })
            j = res.data.map((value) => ({
                "severity" : value.security_vulnerability.severity,
                "package_name" : value.dependency.package.name
            }))
            
            console.log(j)
