name: Remind Dependabot alerts2
on:
  push:
  workflow_dispatch:

jobs:
  dependabot-notifier2:
    runs-on: ubuntu-latest
    permissions:
      security-events: read
    steps:
      - name: Generate token
        id: generate-token
        uses: actions/create-github-app-token@v1
        with:
          app-id: ${{ secrets.APP_ID }}
          private-key: ${{ secrets.PRIVATE_KEY }}

      - name: Get Dependabot alerts
        id: get-dependabot-alerts
        uses: actions/github-script@v7
        with:
          github-token: ${{ steps.generate-token.outputs.token }}
          script: |
            const res = await github.request('GET /repos/{owner}/{repo}/dependabot/alerts', {
              owner: context.repo.owner,
              repo: context.repo.repo,
              headers: {
                'X-GitHub-Api-Version': '2022-11-28'
              }
            })
            return res.data.map((value) => ({
                severity : value.security_vulnerability.severity,
                package_name : value.dependency.package.name
            }))

      - name: Create Slack Message
        id: create-slack-message
        env:
          DEPENDABOT_ALERTS_DATA: ${{ steps.get-dependabot-alerts.outputs.result }}
        uses: actions/github-script@v7
        with:
          script: |
            const {DEPENDABOT_ALERTS_DATA} = process.env
            const alerts_data = JSON.parse(DEPENDABOT_ALERTS_DATA)
            console.log(alerts_data)
            const totalCount = alerts_data.length
            const criticalCount = alerts_data.filter(val => val.severity === 'critical').length
            console.log(`${totalCount}, ${criticalCount}`)
