name: Remind Dependabot alerts2
on:
  push:
  workflow_dispatch:
env:
  SLACK_USERNAME: DeployBot
  SLACK_ICON: https://github.githubassets.com/images/modules/logos_page/GitHub-Mark.png
  SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK_URL }}

jobs:
  dependabot-notifier2:
    runs-on: ubuntu-latest
    permissions:
      security-events: read
    steps:
      - name: GitHub CLI
        id: get-dependabot-alert
        env:
          GH_TOKEN: ${{ secrets.DEPENDABOT_TOKEN }}
        run: |
          res=$(gh api \
             -H "Accept: application/vnd.github+json" \
             -H "X-GitHub-Api-Version: 2022-11-28" \
             /repos/mtsuchiya/sample01/dependabot/alerts?state=open \
             --jq \
             'map({
                severity: .security_vulnerability.severity,
                package_name: .dependency.package.name,
                created_at: .created_at
              })')
          echo "DEPENDABOT_ALERTS<<EOF" >> "$GITHUB_OUTPUT"
          echo $res >> "$GITHUB_OUTPUT"
          echo "EOF" >> "$GITHUB_OUTPUT"

      - name: get count
        id: get-count
        run: |
          dependabot_alerts='${{ steps.get-dependabot-alert.outputs.DEPENDABOT_ALERTS }}'
          echo "TOTAL_COUNT=$(echo $dependabot_alerts | jq 'length')" >> "$GITHUB_OUTPUT"
          echo "CRITICAL_COUNT=$(echo $dependabot_alerts | jq '.[] | select(.severity == "critical") | .severity' | wc -l)" >> "$GITHUB_OUTPUT"
          message=$(cat << EOS
          Dependabot alerts を確認してください。
          https://github.com/mtsuchiya/sample01/security/dependabot
          TOTAL_COUNT=$(echo $dependabot_alerts | jq 'length')
          EOS
          )
          echo "SLACK_MESSAGE<<EOF" >> "$GITHUB_OUTPUT"
          echo $message >> "$GITHUB_OUTPUT"
          echo "EOF" >> "$GITHUB_OUTPUT"

      - name: echo count
        run: |
          echo ${{ steps.get-count.outputs.TOTAL_COUNT }}
          echo ${{ steps.get-count.outputs.SLACK_MESSAGE }}

      - name: Slack Notification Dependabot alerts
        uses: rtCamp/action-slack-notify@v2
        if: steps.vulunabilities-result.outputs.SLACK_MESSAGE != ''
        env:
          SLACK_TITLE: Dependabot
          SLACK_COLOR: good
          SLACK_MESSAGE: ${{ steps.get-count.outputs.SLACK_MESSAGE }}
